<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="resources\arrow-run.png" />
    <None Remove="resources\arrow.png" />
    <None Remove="resources\broom.png" />
    <None Remove="resources\copy.png" />
    <None Remove="resources\folder.png" />
    <None Remove="resources\paper.png" />
    <None Remove="resources\paste.png" />
    <None Remove="resources\right-arrow.png" />
    <None Remove="resources\save.png" />
    <None Remove="resources\scissors.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources\arrow-run.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\arrow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\broom.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\copy.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\folder.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\paper.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\paste.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\right-arrow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\save.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\scissors.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="resources\Справка\Index.hhk">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Intro.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Intro2.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Intro3.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\new_project.chm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\new_project.chw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\new_project.hhp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Table of Contents.hhc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Открыть.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Регулярные выражения.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Создать.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Сохранить.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\Справка\Файл, справка.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
